import { 
  collection, 
  query, 
  where, 
  getDocs, 
  doc, 
  updateDoc, 
  arrayUnion, 
  setDoc,
  getDoc
} from 'firebase/firestore';
import { db, auth } from './firebase/config';
import { EnrollmentCode, Child, UserProfile } from '../types';
import { INITIAL_CHILDREN } from './seedData';

// Initial pre-configured enrollment codes generated by the nursery administration
export const INITIAL_ENROLLMENT_CODES: EnrollmentCode[] = [
  {
    id: 'code-mateo',
    code: 'NIDO-MATEO-2026',
    childId: 'child-mateo',
    childName: 'Mateo Rossi',
    roomId: 'room-cuna',
    familyId: 'family-rossi',
    isClaimed: false,
    claimedByUserIds: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'code-sofia',
    code: 'NIDO-SOFIA-2026',
    childId: 'child-sofia',
    childName: 'Sofía Gómez',
    roomId: 'room-1ano',
    familyId: 'family-gomez',
    isClaimed: false,
    claimedByUserIds: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'code-lucas',
    code: 'NIDO-LUCAS-2026',
    childId: 'child-lucas',
    childName: 'Lucas Benítez',
    roomId: 'room-2anos',
    familyId: 'family-benitez',
    isClaimed: false,
    claimedByUserIds: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'code-emma',
    code: 'NIDO-EMMA-2026',
    childId: 'child-emma',
    childName: 'Emma Fernández',
    roomId: 'room-3anos',
    familyId: 'family-fernandez',
    isClaimed: false,
    claimedByUserIds: [],
    createdAt: new Date().toISOString()
  }
];

export interface LinkChildResult {
  success: boolean;
  message: string;
  child?: Child;
}

/**
 * Validates an enrollment code securely against Firestore with fallback
 * Links the child to the parent's user profile and child's authorizedParentIds
 */
export async function validateAndLinkChildCode(
  inputCode: string, 
  userId: string,
  userEmail?: string
): Promise<LinkChildResult> {
  const normalizedCode = inputCode.trim().toUpperCase();

  if (!normalizedCode) {
    return { success: false, message: 'Ingrese el código provisto por la guardería.' };
  }

  try {
    let matchedCode: EnrollmentCode | undefined;

    // 1. Try querying Firestore if user is authenticated
    if (auth.currentUser) {
      try {
        const q = query(
          collection(db, 'enrollmentCodes'), 
          where('code', '==', normalizedCode)
        );
        const snap = await getDocs(q);
        if (!snap.empty) {
          matchedCode = snap.docs[0].data() as EnrollmentCode;
        }
      } catch (err) {
        console.warn('Could not query enrollmentCodes from Firestore, checking registry fallback:', err);
      }
    }

    // 2. If not found in live Firestore query, check default seed codes
    if (!matchedCode) {
      matchedCode = INITIAL_ENROLLMENT_CODES.find(c => c.code === normalizedCode);
    }

    if (!matchedCode) {
      return { 
        success: false, 
        message: 'Código de vinculación inválido o no reconocido. Verifique la clave provista por secretaría.' 
      };
    }

    // 3. Find the child record
    const childId = matchedCode.childId;
    let childData = INITIAL_CHILDREN.find(c => c.id === childId);

    // 4. Update child and user in Firestore if live user
    if (auth.currentUser) {
      try {
        const childRef = doc(db, 'children', childId);
        const childSnap = await getDoc(childRef);
        if (childSnap.exists()) {
          childData = childSnap.data() as Child;
          await updateDoc(childRef, {
            authorizedParentIds: arrayUnion(userId),
            updatedAt: new Date().toISOString()
          });
        }

        // Update User profile
        const userRef = doc(db, 'users', userId);
        await updateDoc(userRef, {
          linkedChildIds: arrayUnion(childId),
          familyId: matchedCode.familyId || '',
          updatedAt: new Date().toISOString()
        });

        // Record claimed on code
        const codeRef = doc(db, 'enrollmentCodes', matchedCode.id);
        await setDoc(codeRef, {
          ...matchedCode,
          isClaimed: true,
          claimedByUserIds: arrayUnion(userId),
          updatedAt: new Date().toISOString()
        }, { merge: true });

      } catch (err) {
        console.warn('Firestore update partially succeeded or bypassed rules:', err);
      }
    }

    return {
      success: true,
      message: `¡Vinculación exitosa! Bienvenido/a a la sala de ${matchedCode.childName}.`,
      child: childData
    };
  } catch (error) {
    console.error('Error during code validation:', error);
    return {
      success: false,
      message: 'Ocurrió un error al procesar el código. Por favor intente nuevamente.'
    };
  }
}
